# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3f441ce32fe187f9175282b1e0cdeffdab17fc953cc38403d3396c7669ec5ec42bf0cc39ad6f624e71830ad1b0cb51cb0d189db82364cbf2b42e1d4d88f1a570

test:
  secret_key_base: 4d629794545f3c6661ea2f8eb66c690a705214fef4df9bda1ae35a4e2b6b5de1cfffb20c1fbac12ac528b85d445427e91fa2a1a737d3ced7898b8c08af535c95

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
